### ISSUE TITLE
default fall through command

### ISSUE THREAD

**Issue by csprance** [rohanchandra/javascript-terminal#2]
Would be nice to be able to specify a default action if a command is not found.

**Comment by rohanchandra** [comment]
Interesting idea.

Perhaps an extra parameter can be added to `run` to accept a function to run when no command is found (i.e. a callback).

The default function for this parameter could be the current "command not found" side effect:

```javascript
return {
      output: makeRunnerErrorOutput(emulatorErrorType.COMMAND_NOT_FOUND)
};
```

So the function signature would be something like this:

```javascript
const run = (commandMapping, commandName, commandArgs, notFoundCallback = () => {
      return {
            output: makeRunnerErrorOutput(emulatorErrorType.COMMAND_NOT_FOUND)
      }
}) => { }
```

Happy to accept a PR for this.

**Comment by csprance** [comment]
Ya, that would work. I ended up checking if a terminal command named named default was provided in the commandMapping and then treat that as the default command.

I think your way may be better though.

I also changed the commands to run async by just await some things.

Do you see any issue with having async commands? (Should probably be a different issue)

Digging this lib.

**Comment by csprance** [comment]
PR #3 solves this

**Comment by rohanchandra** [comment]
> Do you see any issue with having async commands? (Should probably be a different issue)

I don't think there would be any issue switching to `async`, the only thing that would need (minor) changes is the demo code and unit tests for asynchronous execution.

**Comment by csprance** [comment]
Happy hacktoberfest
