### ISSUE TITLE
Prompt Yes or No before executing a command?

### ISSUE THREAD

**Issue by px017132** [rohanchandra/javascript-terminal#5]
I need to prompt the user "are you sure you want to do this?" and allow them to enter Y or N to continue executing the command.

Any ideas on how I could achieve this using javascript-terminal?

**Comment by rohanchandra** [comment]
Yes, that is possible as you have control over when the terminal executes a command, as well as the output of the emulator.

It will require some custom logic:

1. Each time the user presses enter, you can add a custom message to the `emulator` (see the [outputs section](https://github.com/rohanchandra/javascript-terminal#outputs)) that has the text '`are you sure you want to do this?'`.

2. When the user presses enter with a command of `'Y'` or `'N'`, you can retrieve the last command (see the [history section](https://github.com/rohanchandra/javascript-terminal#history)) and run the command using `emulator.execute(...)`.
