### ISSUE TITLE
Streaming output of a command to the console 

### ISSUE THREAD

**Issue by boxingblue** [rohanchandra/javascript-terminal#6]
I have a usecase where I want a command to open up a websocket and whatever data comes in on that websocket I would like to display on the terminal output.

Now the problem I have is currently all commands have to look like this:

      return {
        output: OutputFactory.makeTextOutput(input)
      };
    },
    'optDef': {}
  }

They all have to "return" a single TextOutput which doesn't allow me to stream my data onto the console output.

Any ideas on how I can do this?

**Comment by rohanchandra** [comment]
Unfortunately, there's no mechanism to allow for a stream of input as this project was designed with simpler use-cases in mind.
